services:
  garage-backend:
    build: .
    container_name: garage-backend
    ports:
      - "5003:3000"
    environment:
      APP_PORT: 3000
      APP_HOST: http://localhost:5000
      NODE_ENV: development
      OLLAMA_API_HOST: http://ollama:11434
      TEST_MODE: "true"
      CORS_ENABLED: "true"
      CORS_DOMAINS: http://localhost:5200
      FRONTEND_HOST: http://localhost:5200
      REQUEST_BODY_LIMIT: 5mb
      SESSION_SECRET: secret
      JWT_SECRET: jwt_secret
      MYSQL_DB_HOST: mysql
      MYSQL_DB_PORT: 3306
      MYSQL_DB: garage
      MYSQL_USER: pricing_engine
      MYSQL_PASSWORD: secret
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
      LOKI_HOST: http://loki:3100
      APP_NAME: garage-backend
    networks:
      - garage-network
    restart: always
    depends_on:
      - ollama
      - loki

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    networks:
      - garage-network
    ports:
      - "11434:11434"
    restart: unless-stopped
    volumes:
      - ollama-data:/root/.ollama
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
        limits:
          cpus: 4.0
          memory: 16g

  streamlit-client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: streamlit-client
    ports:
      - "8501:8501"
    environment:
      BACKEND_URL: http://garage-backend:3000/api/v1/chat/
      IMAGE_GEN_URL: http://host.docker.internal:5001
    depends_on:
      - garage-backend
    networks:
      - garage-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: pricing_engine
      PMA_PASSWORD: secret
    ports:
      - '8080:80'
    networks:
      - garage-network
    restart: always

  loki:
    image: grafana/loki:2.9.3
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - loki-storage:/loki
    networks:
      - garage-network
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3001"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana-datasources.yml:/etc/grafana/provisioning/datasources/loki-datasource.yml
    networks:
      - garage-network
    depends_on:
      - loki
    restart: always

volumes:
  ollama-data:
  loki-storage:
  grafana-storage:

networks:
  garage-network:
    driver: bridge
