version: "3.9"

services:
  garage-backend:
    build: .
    container_name: garage-backend
    ports:
      - "5003:3000"
    environment:
      APP_PORT: 3000
      APP_HOST: http://localhost:5000
      NODE_ENV: development
      OLLAMA_API_HOST: http://ollama:11434
      TEST_MODE: "true"
      CORS_ENABLED: "true"
      CORS_DOMAINS: http://localhost:5200
      FRONTEND_HOST: http://localhost:5200
      REQUEST_BODY_LIMIT: 5mb
      SESSION_SECRET: secret
      JWT_SECRET: jwt_secret
      MYSQL_DB_HOST: mysql
      MYSQL_DB_PORT: 3306
      MYSQL_DB: garage
      MYSQL_USER: pricing_engine
      MYSQL_PASSWORD: secret
    networks:
      - garage-network
    restart: always
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    networks:
      - garage-network
    ports:
      - "11434:11434"
    restart: unless-stopped
    volumes:
      - ollama-data:/root/.ollama

  streamlit-client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: streamlit-client
    ports:
      - "8501:8501"
    environment:
      BACKEND_URL: http://garage-backend:3000/api/v1/price/get-ai-prices
    depends_on:
      - garage-backend
    networks:
      - garage-network
      
volumes:
  ollama-data:

networks:
  garage-network:
    driver: bridge
