export enum ValidationTypes
{
    SINGLE = "SINGLE",
    ALL = "ALL",
    ATTRIBUTES = "ATTRIBUTES",
    SINGLE_ATTRIBUTES = "SINGLE_ATTRIBUTES",
    BULK = "BULK",
    COMPANY_METRICS_SINGLE = "COMPANY_METRICS_SINGLE",
    LOCATION_METRICS_SINGLE = "LOCATION_METRICS_SINGLE",
    CUSTOMER_METRICS_SINGLE = "CUSTOMER_METRICS_SINGLE"
}
